# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envs < Formula
  desc "CLI-first management of your environment secrets."
  homepage "https://envsecrets.com"
  version "1.1.15"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/envsecrets/envsecrets/releases/download/v1.1.15/envsecrets_1.1.15_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "83e4529cb28a94d74e3a4c99b18f14b5355db22dcc4d74e7cb99eaae7ddb539a"

      def install
        bin.install "envs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/envsecrets/envsecrets/releases/download/v1.1.15/envsecrets_1.1.15_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "e629ca8cdd72d839fd268664b7744b4a89e4198d17990b1d1db17d4e4ef66e4d"

      def install
        bin.install "envs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/envsecrets/envsecrets/releases/download/v1.1.15/envsecrets_1.1.15_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "df1942afbe6321e864917fc042f15789ac8144549be37d51a787a99b334fcb10"

      def install
        bin.install "envs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/envsecrets/envsecrets/releases/download/v1.1.15/envsecrets_1.1.15_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "87fdabf1b39533e9cef77e84be19635f75da2f4cc8a86cc6162f9ba36244cfbb"

      def install
        bin.install "envs"
      end
    end
  end
end
