# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envs < Formula
  desc "CLI-first management of your environment secrets."
  homepage "https://envsecrets.com"
  version "1.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/envsecrets/cli/releases/download/v1.1.3/cli_1.1.3_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "3d2a525bfbb01c732dae661fdf5f6d827910f6063d389a7f1485f10bfba757c9"

      def install
        bin.install "envs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/envsecrets/cli/releases/download/v1.1.3/cli_1.1.3_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b671bc6895109055d38cb248a72ebf2bdd705c3bb1da3e2c5ca57905f87300c4"

      def install
        bin.install "envs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/envsecrets/cli/releases/download/v1.1.3/cli_1.1.3_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "9807b8c2e5c1881c8534b84c7f37aca9c5d9aa8532fa1d28ff403fdce2c03bd2"

      def install
        bin.install "envs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/envsecrets/cli/releases/download/v1.1.3/cli_1.1.3_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b4b3286cb595e80c7b604a6f5c3d119bf58d221b2c8d2843a27fd6558590d986"

      def install
        bin.install "envs"
      end
    end
  end
end
