# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envsecrets < Formula
  desc "CLI-first management of your environment secrets."
  homepage "https://envsecrets.com"
  version "0.0.14"

  on_macos do
    url "https://github.com/envsecrets/cli/releases/download/v0.0.14/cli_0.0.14_darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "e1b6d035cb69f3b1d41122cad10d12418d9d4806c50889717bb1ae0c05d0fdae"

    def install
      bin.install "cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/envsecrets/cli/releases/download/v0.0.14/cli_0.0.14_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "5b9ccd487c120865aa6124d222edb2d0d2a76c60a594b1f2ef6032765e563ce8"

      def install
        bin.install "envsecrets"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/envsecrets/cli/releases/download/v0.0.14/cli_0.0.14_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "646a17a32bdb8f2fd290b21ac77f5916141a9384966f893e449000ec7c01d0e3"

      def install
        bin.install "envsecrets"
      end
    end
  end
end
